#!/bin/bash

if [[ $(hostname -s) =~ ^(kepler05|kepler06|kepler07)$ ]]; then
    expectedcount=8
    expectedspeed=2133
    expectedsize=16384
else
    expectedcount=8
    expectedspeed=1600
    expectedsize=16384
fi

count=$(/usr/sbin/dmidecode -t 17 | /bin/grep 'Configured Clock.*MHz' | /usr/bin/wc | /bin/awk '{print $1}')
speedcount=$(/usr/sbin/dmidecode -t 17 | /bin/grep 'Configured Clock.*MHz' | /bin/grep $expectedspeed | /usr/bin/wc | /bin/awk '{print $1}')
sizecount=$(/usr/sbin/dmidecode -t 17 | /bin/grep 'Size.*MB' | /bin/grep $expectedsize | /usr/bin/wc | /bin/awk '{print $1}')

exitstatus=0

if [ "$count" -ne "$expectedcount" ]
then
    /bin/echo "Not enough DIMMs: $expectedcount expected, $count found"
    exitstatus=-1
fi

if [ "$speedcount" -ne "$expectedcount" ]
then
    /bin/echo "Not enough DIMMs of the correct speed: $expectedcount expected, $speedcount found"
    exitstatus=-1
fi

if [ "$sizecount" -ne "$expectedcount" ]
then
    /bin/echo "Not enough DIMMs of the correct size: $expectedcount expected, $sizecount found"
    exitstatus=-1
fi

exit $exitstatus
